export const Star = '*';
export const Hash = '#';
export const Backtick = '`';
export const EmptyLine = '\n\n';
export const NewLine = '\n';
export const SoftBreak = ' ';
export const BoldIndicator = '**';
export const ItalicIndicator = '*';
export const HeadingIndicator = '#';
